spring:
  application:
    name: inventoryservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Inventory Service version 1.0
server:
  port: 21905